services:

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  server:
    image: tanjim100/ci-server:latest
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - server/.env

    depends_on:
      - redis

  worker:
    image: tanjim100/ci-worker:latest
    restart: unless-stopped

    env_file:
      - worker/.env

    depends_on:
      - redis
      - server

  runner:
    image: tanjim100/ci-runner:latest
    restart: unless-stopped

    privileged: true

    ports:
      - "7000:7000"

    env_file:
      - runner/.env

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

    depends_on:
      - server

  frontend:
    image: tanjim100/ci-frontend:latest
    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      - server