version: "3.8"

services:

  redis:
    image: redis:7
    restart: always

  server:
    image: tanjim100/ci-server:latest
    restart: always
    env_file:
      - server/.env
    depends_on:
      - redis

  worker:
    image: tanjim100/ci-worker:latest
    restart: always
    env_file:
      - worker/.env
    depends_on:
      - redis
      - server

  runner:
    image: tanjim100/ci-runner:latest
    restart: always
    privileged: true
    env_file:
      - runner/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - server

  frontend:
    image: tanjim100/ci-frontend:latest
    restart: always
    env_file:
      - frontend/.env
    depends_on:
      - server