name: CD Pipeline

on:

  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:

  deploy:

    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Create Server Env
        run: echo '${{ secrets.SERVER_ENV }}' > server/.env

      - name: Create Worker Env
        run: echo '${{ secrets.WORKER_ENV }}' > worker/.env

      - name: Create Runner Env
        run: echo '${{ secrets.RUNNER_ENV }}' > runner/.env

      - name: Create Frontend Env
        run: echo '${{ secrets.FRONTEND_ENV }}' > frontend/.env

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Images
        run: |
          docker build -t tanjim100/ci-server:latest ./server
          docker build -t tanjim100/ci-worker:latest ./worker
          docker build -t tanjim100/ci-runner:latest ./runner
          docker build -t tanjim100/ci-frontend:latest ./frontend

      - name: Push Images
        run: |
          docker push tanjim100/ci-server:latest
          docker push tanjim100/ci-worker:latest
          docker push tanjim100/ci-runner:latest
          docker push tanjim100/ci-frontend:latest

      - name: Deploy EC2
        uses: appleboy/ssh-action@v1.2.2

        with:

          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}

          script: |

            set -e

            cd ~/mini-ci/puku-editor-Tanjim-Haider-8

            git pull origin main

            cat > server/.env <<'EOF'
            ${{ secrets.SERVER_ENV }}
            EOF

            cat > worker/.env <<'EOF'
            ${{ secrets.WORKER_ENV }}
            EOF

            cat > runner/.env <<'EOF'
            ${{ secrets.RUNNER_ENV }}
            EOF

            cat > frontend/.env <<'EOF'
            ${{ secrets.FRONTEND_ENV }}
            EOF

            docker compose -f docker-compose.prod.yml pull

            docker compose -f docker-compose.prod.yml down

            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f