name: CD Pipeline

on:

  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------
      # Create env files
      # ----------------------------

      - run: echo "${{ secrets.SERVER_ENV }}" > server/.env
      - run: echo "${{ secrets.WORKER_ENV }}" > worker/.env
      - run: echo "${{ secrets.RUNNER_ENV }}" > runner/.env
      - run: echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env

      # ----------------------------
      # Login DockerHub
      # ----------------------------

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # ----------------------------
      # Build Images
      # ----------------------------

      - name: Build Images
        run: docker compose -f docker-compose.yml build

      # ----------------------------
      # Push Images
      # ----------------------------

      - name: Push Images
        run: docker compose -f docker-compose.yml push

      # ----------------------------
      # SSH into EC2
      # ----------------------------

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.2.2

        with:

          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}

          script: |

            cd ~/mini-ci/puku-editor-Tanjim-Haider-8

            echo "Updating Repository..."
            git pull origin main

            echo "Creating Environment Files..."

            cat > server/.env <<'EOF'
            ${{ secrets.SERVER_ENV }}
            EOF

            cat > worker/.env <<'EOF'
            ${{ secrets.WORKER_ENV }}
            EOF

            cat > runner/.env <<'EOF'
            ${{ secrets.RUNNER_ENV }}
            EOF

            cat > frontend/.env <<'EOF'
            ${{ secrets.FRONTEND_ENV }}
            EOF

            echo "Pulling Latest Images..."
            docker compose pull

            echo "Stopping Old Containers..."
            docker compose down

            echo "Starting New Containers..."
            docker compose up -d --remove-orphans

            echo "Removing Unused Images..."
            docker image prune -af

            echo "Deployment Completed Successfully"